-- MySQL Script generated by MySQL Workbench
-- Tue Jan 25 22:55:19 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cs360db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cs360db` ;

-- -----------------------------------------------------
-- Schema cs360db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cs360db` DEFAULT CHARACTER SET utf8 ;
USE `cs360db` ;

-- -----------------------------------------------------
-- Table `cs360db`.`civilians`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cs360db`.`civilians` ;

CREATE TABLE IF NOT EXISTS `cs360db`.`civilians` (
  `account_no` INT NOT NULL,
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(16) NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `debt` DOUBLE NOT NULL,
  `expiration_date` DATE NOT NULL,
  `credit_limit` DOUBLE NOT NULL,
  `balance` DOUBLE NOT NULL,
  PRIMARY KEY (`account_no`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `cs360db`.`companies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cs360db`.`companies` ;

CREATE TABLE IF NOT EXISTS `cs360db`.`companies` (
  `account_no` INT NOT NULL,
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(16) NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `debt` DOUBLE NOT NULL,
  `exp_date` DATE NOT NULL,
  `credit_limit` DOUBLE NOT NULL,
  `balance` DOUBLE NOT NULL,
  PRIMARY KEY (`account_no`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `cs360db`.`dealers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cs360db`.`dealers` ;

CREATE TABLE IF NOT EXISTS `cs360db`.`dealers` (
  `account_no` INT NOT NULL,
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(16) NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `debt` DOUBLE NOT NULL,
  `earnings` DOUBLE NOT NULL,
  `commission` DOUBLE NOT NULL,
  PRIMARY KEY (`account_no`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `cs360db`.`transactions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cs360db`.`transactions` ;

CREATE TABLE IF NOT EXISTS `cs360db`.`transactions` (
  `transactionID` INT NOT NULL,
  `dealerName` VARCHAR(20) NOT NULL,
  `dealerAccount_no` INT NOT NULL,
  `customerName` VARCHAR(20) NOT NULL,
  `customerAccount_no` INT NOT NULL,
  `date` DATE NOT NULL,
  `amount` DOUBLE NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`transactionID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `cs360db`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cs360db`.`users` ;

CREATE TABLE IF NOT EXISTS `cs360db`.`users` (
  `account_no` INT NOT NULL,
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(16) NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `debt` DOUBLE NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`account_no`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
